[tool.pyright]
pythonVersion = "3.9"
pythonPlatform = "Darwin"
include = ["app"]
exclude = ["tests", "**/__pycache__"]
reportMissingImports = "warning"
reportMissingTypeStubs = false
typeCheckingMode = "basic"

[tool.black]
line-length = 88
target-version = ['py39']
include = '\.pyi?$'
extend-exclude = '''
/(
  # directories
  \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | build
  | dist
)/
'''

[tool.mypy]
python_version = "3.9"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true
